name: adminer
home: https://github.com/drycc-addons/adminer
apiVersion: v2
dependencies:
  - name: common
    repository: oci://registry.drycc.cc/charts
    version: ~1.1.1
description: Database management in a single PHP file.
maintainers:
  - name: Drycc Team
    email: engineering@drycc.com
version: v1.0.0
