apiVersion: v1
kind: Service
metadata:
  name: drycc-adminer
  annotations:
    {{- with .Values.service.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    heritage: drycc
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: drycc-adminer
